site_name: StoreFront SDK Documentation
site_description: StoreFront SDK Reference
theme_dir: theme_multi
markdown_extensions:
  - admonition
  - codehilite(guess_lang=false)
  - toc(permalink=true)
  - footnotes
  - meta

pages:
- Overview: index.md
- StoreFront Web API:
   - Overview: overview.md
   - How the API works: how-the-api-works.md
   - Requests: requests.md
   - Using configuration elements: using-configuration-elements.md
- StoreFront Store Service SDK:
   - StoreFront Customization SDK: customization-sdk.md
   - Getting started with the SDK: getting-started-with-the-sdk.md
   - Customization interfaces: customization-interfaces.md
   - Known issues: known-issues.md
   - Samples: samples.md
- StoreFront Authentication SDK:
   - Authentication Software Development Kit: storefront-services-authentication-sdk.md
   - Citrix Common Forms Authentication API: citrix-common-forms-authentication-api.md
   - CitrixAuth Authentication Scheme: citrixauth-authentication-scheme.md
   - Citrix Common Authentication Forms Language: common-authentication-forms-language.md
   - Security Token Services API: security-token-services-api.md
   - StoreFront Authentication Form Generation: authentication-form-generation.md
   - Known Issues: known-issues-auth.md
   - Third Party Notices: storeFront-authentication-sdk-thirdparty.md
   - Sample Certificate Identity Declaration: sample-certificate-identity-declaration.md
   - Sample Magic Word: magic-word-sample.md
   - Sample Test Forms: sample-test-forms.md
