site_name: Citrix XenApp and XenDesktop SDK
site_description: Reference guide for Citrix XenApp and XenDesktop SDK
theme_dir: theme
markdown_extensions:
  - admonition
  - codehilite
  - toc:
     anchorlink: True

pages:
- Overview: index.md
- Understanding the XenDesktop Administration Model: understanding-xendesktop-administration-model.md
- Getting Started Guide: getting-started.md
- Examples:
  - Creating a catalog: creating-a-catalog.md
  - Creating and configuring a host: creating-and-configuring-a-host.md
  - Creating a PvD Desktop: creating-a-pvd-desktop.md
  - Getting load balancing information: getting-load-balancing-information.md
