site_name: StoreFront SDK Documentation
site_description: StoreFront SDK Reference
theme_dir: theme_multi
markdown_extensions:
  - admonition
  - codehilite
  - toc:
     anchorlink: True

pages:
- StoreFront SDK: index.md
- Overview: overview.md
- How the API works: how-the-api-works.md
- Requests: requests.md
- Using configuration elements: using-configuration-elements.md
